name: Release Builder
# Build a stable release on a tag v* newly pushed

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  prepare-build:
    runs-on: 'ubuntu-latest'
    outputs:
      VERSION_TAG: ${{ steps.get_tag.outputs.VERSION_TAG }}
      CURRENT_SHA: ${{ steps.current_commit.outputs.CURRENT_SHA }}
      PREV_RELEASE_SHA: ${{ steps.previous_commit.outputs.PREV_RELEASE_SHA }}
      COMMIT_LOGS: ${{ steps.commit_logs.outputs.COMMIT_LOGS }}
      PREV_TAG_NAME: ${{ steps.previous_commit.outputs.PREV_TAG_NAME }}
    steps:
      - name: Get tag name (${{ github.ref }})
        id: get_tag
        run: |
          version_tag=$(echo ${GITHUB_REF/refs\/tags\//} | sed -r 's/^refs\/(heads|tags)\///' | sed -r 's/[-\/]+/_/g')
          echo "VERSION_TAG=$version_tag"
          echo "VERSION_TAG=$version_tag" >> $GITHUB_OUTPUT

      - name: Clone Repository (${{ steps.get_tag.outputs.VERSION_TAG }})
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get previous release
        id: last_release
        uses: InsonusK/get-latest-release@v1.1.0
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"
          view_top: 1

      - name: Curren commit
        id: current_commit
        run: |
          commit_count=$(git rev-list --count HEAD)
          current_sha=$(git rev-parse --short HEAD)
          echo "COMMIT_COUNT=$commit_count"
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_OUTPUT
          echo "CURRENT_SHA=$current_sha"
          echo "CURRENT_SHA=$current_sha" >> $GITHUB_OUTPUT

      - name: Previous commit
        id: previous_commit
        run: |
          commit_count_diff=$(git rev-list --count "${{ steps.last_release.outputs.tag_name }}"..HEAD)

          # Fake at least 1 commits (to avoid no changes)
          if [ "${commit_count_diff}" -eq 0 ]; then
            commit_count_diff=1
          fi

          echo "commit_count_diff=$commit_count_diff"
          prev_release_sha=$(git rev-parse --short HEAD~$commit_count_diff)
          echo "PREV_RELEASE_SHA=$prev_release_sha"
          echo "PREV_RELEASE_SHA=$prev_release_sha" >> $GITHUB_OUTPUT
          echo "PREV_TAG_NAME=${{ steps.last_release.outputs.tag_name }}"
          echo "PREV_TAG_NAME=${{ steps.last_release.outputs.tag_name }}" >> $GITHUB_OUTPUT

      - name: Commit logs
        id: commit_logs
        run: |
          echo "COMMIT_LOGS<<{delimiter}
          $(curl -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/xdwil/komikku/compare/${{ steps.previous_commit.outputs.PREV_RELEASE_SHA }}...${{ steps.current_commit.outputs.CURRENT_SHA }}" \
            | jq '[.commits[]|{message:(.commit.message | split("\n")), username:.author.login}]' \
            | jq -r '.[]|"- \(.message | first) (@\(.username))"')
          {delimiter}" >> $GITHUB_OUTPUT

  build-app:
    name: Build release app
    runs-on: 'ubuntu-latest'
    needs: prepare-build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Clone Repository (${{ needs.prepare-build.outputs.VERSION_TAG }})
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Check code format
        run: ./gradlew spotlessCheck

      - name: Build app
        run: ./gradlew assembleRelease -Penable-updater

      - name: Run unit tests
        run: ./gradlew testReleaseUnitTest

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: |
            app/build/outputs/apk/release/app-arm64-v8a-release-unsigned.apk
            app/build/outputs/apk/release/app-armeabi-v7a-release-unsigned.apk
          retention-days: 1

      - name: Upload mapping
        uses: actions/upload-artifact@v4
        with:
          name: mapping-${{ github.sha }}
          path: app/build/outputs/mapping/release

  release-app:
    runs-on: 'ubuntu-latest'
    needs:
      - prepare-build
      - build-app
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: apks
          path: app/build/outputs/apk/release

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: '35.0.1'

      - name: Get SHA & clean up build artifacts
        id: get_sha
        run: |
          set -e

          mv app/build/outputs/apk/release/app-arm64-v8a-release-unsigned-signed.apk Komikku-arm64-v8a-${{ needs.prepare-build.outputs.VERSION_TAG }}.apk
          sha=`sha256sum Komikku-arm64-v8a-${{ needs.prepare-build.outputs.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_OUTPUT

          mv app/build/outputs/apk/release/app-armeabi-v7a-release-unsigned-signed.apk Komikku-armeabi-v7a-${{ needs.prepare-build.outputs.VERSION_TAG }}.apk
          sha=`sha256sum Komikku-armeabi-v7a-${{ needs.prepare-build.outputs.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.prepare-build.outputs.VERSION_TAG }}
          name: Komikku ${{ needs.prepare-build.outputs.VERSION_TAG }}
          body: |
            [![GitHub downloads](https://img.shields.io/github/downloads/xdwil/komikku/${{ needs.prepare-build.outputs.VERSION_TAG }}/total?label=Downloaded&labelColor=27303D&color=0D1117&logo=github&logoColor=FFFFFF&style=flat)](https://github.com/xdwil/komikku/releases/${{ needs.prepare-build.outputs.VERSION_TAG }})
            #### What's Changed
            ##### New

            ##### Improve

            ##### Fix

            ${{ needs.prepare-build.outputs.COMMIT_LOGS }}

            ##### Based on

            **Full Changelog**: [xdwil/komikku@${{ needs.prepare-build.outputs.PREV_TAG_NAME }}...${{ needs.prepare-build.outputs.VERSION_TAG }}](https://github.com/xdwil/komikku/compare/${{ needs.prepare-build.outputs.PREV_TAG_NAME }}...${{ needs.prepare-build.outputs.VERSION_TAG }})

            ---

            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | arm64-v8a | ${{ steps.get_sha.outputs.APK_ARM64_V8A_SHA }} |
            | armeabi-v7a | ${{ steps.get_sha.outputs.APK_ARMEABI_V7A_SHA }} |

            ### If you are unsure which apk to download then go with `Komikku-arm64-v8a-${{ needs.prepare-build.outputs.VERSION_TAG }}.apk`
          files: |
            Komikku-arm64-v8a-${{ needs.prepare-build.outputs.VERSION_TAG }}.apk
            Komikku-armeabi-v7a-${{ needs.prepare-build.outputs.VERSION_TAG }}.apk
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}