name: PR build check
on:
  #  push:
  #    branches:
  #      - develop
  #    paths-ignore:
  #      - '**.md'
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!i18n-kmk/src/commonMain/moko-resources/**/strings.xml'
      - '!i18n-kmk/src/commonMain/moko-resources/**/plurals.xml'
      - 'i18n-kmk/src/commonMain/moko-resources/base/strings.xml'
      - 'i18n-kmk/src/commonMain/moko-resources/base/plurals.xml'
  # Dispatch or Manual triggers
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build app
    runs-on: 'ubuntu-latest'

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dependency Review
        uses: actions/dependency-review-action@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Check code format
        run: ./gradlew spotlessCheck

      - name: Build app
        if: github.repository == github.event.pull_request.head.repo.full_name
        run: ./gradlew assemblePreview -Penable-updater

      - name: Build app
        if: github.repository != github.event.pull_request.head.repo.full_name
        run: ./gradlew assemblePreview

      - name: Run unit tests
        run: ./gradlew testReleaseUnitTest

      - name: Sign APK
        if: github.repository == github.event.pull_request.head.repo.full_name
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/preview
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: '35.0.1'

      - name: Signed File name
        id: signed_filename
        if: github.repository == github.event.pull_request.head.repo.full_name
        run: |
          echo "SIGNED_TRAIL=-signed" >> $GITHUB_OUTPUT

      - name: Rename apk
        id: current_commit
        run: |
          set -e
          echo "The git ref is: ${{ github.ref }}"
          version_tag=p$(echo ${{ github.ref }} | cut -d '/' -f 3)
          commit_count=$(git rev-list --count HEAD)
          echo "VERSION_TAG=$version_tag"
          echo "VERSION_TAG=$version_tag" >> $GITHUB_OUTPUT
          echo "COMMIT_COUNT=$commit_count"
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_OUTPUT
          
          # Move ARM64 and ARM7 APKs
          mv app/build/outputs/apk/preview/app-arm64-v8a-preview${{ steps.signed_filename.outputs.SIGNED_TRAIL }}.apk Komikku-arm64-v8a-$version_tag-r$commit_count.apk
          mv app/build/outputs/apk/preview/app-armeabi-v7a-preview${{ steps.signed_filename.outputs.SIGNED_TRAIL }}.apk Komikku-armeabi-v7a-$version_tag-r$commit_count.apk

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: komikku-apks
          path: |
            Komikku-arm64-v8a-${{ steps.current_commit.outputs.VERSION_TAG }}-r${{ steps.current_commit.outputs.COMMIT_COUNT }}.apk
            Komikku-armeabi-v7a-${{ steps.current_commit.outputs.VERSION_TAG }}-r${{ steps.current_commit.outputs.COMMIT_COUNT }}.apk
          retention-days: 14

      - name: Upload mapping
        uses: actions/upload-artifact@v4
        with:
          name: mapping-${{ github.sha }}
          path: app/build/outputs/mapping/preview