name: Label PRs

on:
  pull_request:
    types: [opened]

permissions:
  contents: write

jobs:
  label_pr:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Check PR and Add Label
        uses: actions/github-script@v7
        with:
          script: |
            const prAuthor = context.payload.pull_request.user.login;

            if (prAuthor === 'weblate') {
              const labels = ['Translations'];
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: labels
              });
            }