name: Update website

on:
  release:
    types:
      - published
      - deleted
      - edited

jobs:
  update_website:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Update website on release
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy
          repo: xdwil/xdwil.github.io
          ref: "refs/heads/main"
          token: "${{ secrets.BOT_PAT }}"